name: Postman Collection Workflow
on :
  push:
   branches: [main]
  workflow_dispatch:
  schedule:
      - cron: 30 02 * * * #8:00AM IST
      - cron: 00 14 * * * # 7:30 PM everaday

jobs:
  run-postman-tests:
   runs-on: ubuntu-latest
      
   steps:
      
     - name: Checkout the code
       uses: actions/checkout@v5.0.0
    
     - name: Install Node.js and npm
       uses: actions/setup-node@v3.9.1
       with:
        node-version: '22'

     -  name: Install newman and htmlextra
        run: |
              npm install -g newman
              npm install -g newman-reporter-htmlextra

     - name: Run Postman collection
       run: |
              newman  run 'Inwarranty-flow Collection E2E.postman_collection.json' \
              -e QA_Env.postman_environment.json \
              -r cli,htmlextra
            
      

